#!/bin/sh
#

if test -z "$prefix"
then
	echo "You must first source the file spath.sh  ('source spath.sh')"
	exit
fi

autoreconf --force --install --verbose

./configure --enable-debug --enable-developer --prefix=$prefix

make -j7 world
